name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **This repository is not like any other repository. It does not create new releases; it only releases new files.**
        **Forget about scrolling whole release page find files. Just read [Readme.md](../main/README.md#microg-revanced) file and select apps you want download.**
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        [Revanced Extended anddea](https://github.com/anddea/revanced-patches/releases)
        [Revanced Extended for Android 6 & 7](https://github.com/kitadai31/revanced-patches-android6-7/releases)
        [Revanced Extended For Android 5:](https://github.com/d4n3436/revanced-patches-android5/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt

    - name: Align and Sign patched APKs
      shell: bash 
      run: |
          echo "[+] Aligning and Signing all patched APKs using revanced.jks..."
          
          # Find the latest installed build-tools version
          BUILD_TOOLS=$(ls -d /usr/local/lib/android/sdk/build-tools/* | sort -V | tail -n 1)
          echo "Using build-tools: $BUILD_TOOLS"

          mkdir -p aligned
          for apk in ./release/*.apk; do
            base=$(basename "$apk")
            
            # --- START PATCH: Version Display ---
            # Extract Version Name and App Label using aapt
            VERSION=$("$BUILD_TOOLS/aapt" dump badging "$apk" 2>/dev/null | grep "versionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
            LABEL=$("$BUILD_TOOLS/aapt" dump badging "$apk" 2>/dev/null | grep "application-label:" | sed -e "s/application-label://" -e "s/'//g")
            
            echo "------------------------------------------------------"
            echo "📦 File:    $base"
            echo "📱 App:     $LABEL"
            echo "🏷️  Version: $VERSION"
            echo "------------------------------------------------------"
            # --- END PATCH ---

            echo "📐 Zipaligning $base ..."
            "$BUILD_TOOLS/zipalign" -f -p 4 "$apk" "aligned/$base"

            echo "🔏 Signing $base ..."
            "$BUILD_TOOLS/apksigner" sign \
              --ks "$KEYSTORE_PATH" \
              --ks-key-alias "$KEY_ALIAS" \
              --ks-pass env:KEYSTORE_PASSWORD \
              --key-pass env:KEY_PASSWORD \
              --in "aligned/$base" \
              --out "./release/$base"
          done

          echo "[+] Verifying final signatures..."
          for apk in ./release/*.apk; do
            echo "🧪 Verifying signature for $(basename "$apk") ..."
            "$BUILD_TOOLS/apksigner" verify --verbose "$apk"
          done
    
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
